---
title: "RuhrMetrics Reading-Group"
subtitle: ""
---

## Contacts

**Bitte beachten Sie, dass sämtliche E-Mail-Dienste der Universität ebenfalls betroffen sind. Daher haben wir die nachfolgenden E-Mail-Adressen für Sie eingerichtet.**


Bei **wichtigen** Fragen wenden Sie sich bitte per E-Mail an uns:

-   [Jens Klenke](mailto:jens.klenke.ude@gmail.com?subject=%5BDeskriptive%20Statistik%5D)
-   [Christoph Hanck](mailto:christoph.hanck@uni-dortmund.de?subject=%5BDeskriptive%20Statistik%5D)

## Testate

Aufgrund der technischen Störungen an der Universität Duisburg-Essen wird das 2. Testat, geplant am 30.11.2022, auf unbestimmte Zeit verschoben. Wir werden Sie über Änderungen frühzeitig informieren.

## Bonuspunkte

Die Bonuspunkte der Kahoots bleiben durch die Störungen unverändert. Zu der Handhabung der Bonuspunkte aus den Testaten können wir gegenwärtig noch keine Auskunft geben, da dem Lehrstuhl selbst noch wichtige Informationen über die Ausfallzeit der Informationsdienste der Universität fehlen. Wir können Ihnen aber versichern, dass die gegenwärtige Situation nicht zu Ihrem Nachteil ausgelegt wird. Sobald wir nähere Informationen haben, werden wir diese sowohl in Vorlesung und Übung als auch hier auf der Seite verbreiten.

## Kahoot!

Ab Mittwoch, den 7.12.2022, werden sowohl in der Vorlesung als auch in der Übung wieder Kahoots durchgeführt. Bitte sorgen Sie mit ihrem Mobilfunknetz für eine entsprechende Internetanbindung. Das Uninetzwerk eduroam steht bis auf Weiteres nicht zur Verfügung.

## Discord: Diskussions- und Nachrichtenforum

Bitte nutzen Sie den Channel #diskussion.

<iframe src="https://e.widgetbot.io/channels/1046886827304419368/1046886827304419371" height="600" width="100%">

</iframe>

## Weitere Module

Wir möchten Sie außerdem auf folgende Websites mit Lehrmaterialien zu weiteren Modulen aufmerksam machen:

### Lehrstuhl für Ökonometrie

#### Bachelorveranstaltungen 

-   [Einführung in die Ökonometrie](https://mca91.github.io/Eidoe22/)

##### Masterveranstaltungen 

-   [Methoden der Ökonometrie](https://github.com/karo93/Methoden2223)
-   [Recent Developments in Econometrics](https://jens-klenke.github.io/RDIE_WiSe_22/)


#### Lehrstuhl UEE (Prof. Ziel)

-   [Umweltökonomik und Erneuerbare Energien](https://uee.berrisch.biz)
